no-daemon
keep-in-foreground
interface=bridge100
listen-address=192.168.122.1
no-hosts
dhcp-range=192.168.122.2,192.168.122.254
dhcp-authoritative
log-dhcp
log-queries=extra

dhcp-vendorclass=set:efi-amd64-http,HTTPClient:Arch:00016
dhcp-option-force=tag:efi-amd64-http,60,HTTPClient
dhcp-boot=tag:efi-amd64-http,"http://192.168.122.1/EFI/BOOT/BOOTX64.EFI"

dhcp-vendorclass=set:efi-aarch64-http,HTTPClient:Arch:00019
dhcp-option-force=tag:efi-aarch64-http,60,HTTPClient
dhcp-boot=tag:efi-aarch64-http,"http://192.168.122.1/EFI/BOOT/BOOTAA64.EFI"

###
# AARCH64 UEFI HTTP Boot
#
# dnsmasq-dhcp: 2404829736 vendor class: HTTPClient:Arch:00019:UNDI:003000
# dnsmasq-dhcp: 2404829736 DHCPDISCOVER(bridge100) 52:54:00:12:34:56
# dnsmasq-dhcp: 2404829736 tags: bridge100
# dnsmasq-dhcp: 2404829736 DHCPOFFER(bridge100) 192.168.122.76 52:54:00:12:34:56
# dnsmasq-dhcp: 2404829736 requested options: 1:netmask, 2:time-offset, 3:router, 4, 5,
# dnsmasq-dhcp: 2404829736 requested options: 6:dns-server, 12:hostname, 13:boot-file-size,
# dnsmasq-dhcp: 2404829736 requested options: 15:domain-name, 17:root-path, 18:extension-path,
# dnsmasq-dhcp: 2404829736 requested options: 22:max-datagram-reassembly, 23:default-ttl,
# dnsmasq-dhcp: 2404829736 requested options: 28:broadcast, 40:nis-domain, 41:nis-server,
# dnsmasq-dhcp: 2404829736 requested options: 42:ntp-server, 43:vendor-encap, 50:requested-address,
# dnsmasq-dhcp: 2404829736 requested options: 51:lease-time, 54:server-identifier, 58:T1,
# dnsmasq-dhcp: 2404829736 requested options: 59:T2, 60:vendor-class, 104, 67:bootfile-name,
# dnsmasq-dhcp: 2404829736 requested options: 97:client-machine-id
# dnsmasq-dhcp: 2404829736 next server: 192.168.122.1
